# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 178b1f47daf01f8db536df13b09983c1fca668cc6cf3f79443975c16540f448691800daf159b33603c9495bd04135ca8022e2ae1b30186969b5f920b166c5046

test:
  secret_key_base: 4f583032effdc57a7145307c25a43d56d094ade7a3e5a53ef6b607f1d7af714f49249e86c1d46c4720b258928015f47df68437e182bc62cbbd582b413223aa15

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
